#!/bin/sh
#
# load devices
#

case "$1" in
  start)
	  modprobe snd-bcm2835
	  modprobe rt2800usb
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
